export const GAME_EVENT_TYPES = Object.freeze({
  MATCH_STARTED: 'MATCH_STARTED',
  MATCH_ENDED: 'MATCH_ENDED',
  GAME_SNAPSHOT: 'GAME_SNAPSHOT',
  CLOCK_UPDATED: 'CLOCK_UPDATED',
  HERO_LEVEL_CHANGED: 'HERO_LEVEL_CHANGED',
  ITEM_ADDED: 'ITEM_ADDED',
  ITEM_REMOVED: 'ITEM_REMOVED',
  GOLD_CHANGED: 'GOLD_CHANGED',
  ECONOMY_UPDATED: 'ECONOMY_UPDATED',
  HERO_VITALS_CHANGED: 'HERO_VITALS_CHANGED',
  HERO_DIED: 'HERO_DIED',
  HERO_RESPAWNED: 'HERO_RESPAWNED',
  ULTIMATE_CHANGED: 'ULTIMATE_CHANGED',
  CONTEXT_UPDATED: 'CONTEXT_UPDATED',
  ROLE_CONTEXT_UPDATED: 'ROLE_CONTEXT_UPDATED',
  ROLE_CONTEXT_CAPABILITIES_UPDATED: 'ROLE_CONTEXT_CAPABILITIES_UPDATED',
  ROSTER_UPDATED: 'ROSTER_UPDATED',
  ABILITY_STATE_CHANGED: 'ABILITY_STATE_CHANGED',
  COMBAT_STATS_UPDATED: 'COMBAT_STATS_UPDATED',
  STATUS_EFFECTS_UPDATED: 'STATUS_EFFECTS_UPDATED',
  WARD_STATE_UPDATED: 'WARD_STATE_UPDATED',
  DAMAGE_UPDATED: 'DAMAGE_UPDATED',
  TEAM_SCORE_UPDATED: 'TEAM_SCORE_UPDATED',
  DRAFT_UPDATED: 'DRAFT_UPDATED',
  PLAYER_IDENTIFIED: 'PLAYER_IDENTIFIED',
  MATCH_IDENTIFIED: 'MATCH_IDENTIFIED',
  COACH_TIMER_STARTED: 'COACH_TIMER_STARTED',
  COACH_TIMER_CLEARED: 'COACH_TIMER_CLEARED',
  SCOUTING_UPDATED: 'SCOUTING_UPDATED',
  COACH_SETTINGS_UPDATED: 'COACH_SETTINGS_UPDATED'
});

const KNOWN_TYPES = new Set(Object.values(GAME_EVENT_TYPES));

export function createGameEvent(type, payload = {}, metadata = {}) {
  return {
    type,
    payload: payload && typeof payload === 'object' ? payload : {},
    ...metadata
  };
}

export function isGameEvent(value) {
  return Boolean(value && typeof value === 'object' && KNOWN_TYPES.has(value.type));
}

export function normalizeItemId(value) {
  if (typeof value !== 'string' || !value.trim()) return null;
  const id = value.trim().toLowerCase();
  return id.startsWith('item_') ? id : `item_${id}`;
}
