import { mkdir, open, readFile, readdir, rename, rm, stat, writeFile } from 'node:fs/promises';
import { basename, join, resolve } from 'node:path';
import { createHash, randomUUID } from 'node:crypto';

export const RUNTIME_MODES = Object.freeze({ mock: 'MOCK', replay: 'REPLAY', live: 'LIVE_GEP' });
export const GEP_FEATURE_MANIFEST = Object.freeze({
  manifestVersion: 1,
  required: ['game_info', 'match_info', 'me'],
  optional: ['roster', 'items', 'abilities', 'kill', 'death', 'respawn'],
  experimental: []
});
export const DIAGNOSTIC_CODES = Object.freeze(['OVERWOLF_NOT_CONFIGURED','OVERWOLF_RUNTIME_UNAVAILABLE','DOTA_NOT_RUNNING','GEP_INITIALIZING','GEP_READY','GEP_PARTIAL','GEP_DISCONNECTED','MATCH_NOT_DETECTED','MATCH_ACTIVE','CAPTURE_ACTIVE','CAPTURE_STOPPED','CAPTURE_RECOVERED']);

export function resolveRuntimeMode(value = process.env.DOTA_FLOW_RUNTIME_MODE) {
  const key = String(value ?? '').trim().toLowerCase();
  if (!RUNTIME_MODES[key]) throw Object.assign(new Error('DOTA_FLOW_RUNTIME_MODE must be mock, replay, or live'), { code: 'INVALID_RUNTIME_MODE' });
  return RUNTIME_MODES[key];
}
export function safeError(error) { return { code: String(error?.code ?? 'RUNTIME_ERROR'), message: String(error?.message ?? 'Runtime operation failed').slice(0, 300) }; }
export class RuntimeDiagnostics {
  constructor(limit = 200) { this.limit = limit; this.entries = []; }
  add(code, severity = 'info', details = {}) { const entry = { code, severity, message: details.message ?? code.replaceAll('_',' ').toLowerCase(), remediation: details.remediation ?? null, details: details.details ?? {}, occurredAt: new Date().toISOString() }; this.entries.push(entry); if (this.entries.length > this.limit) this.entries.splice(0, this.entries.length - this.limit); return entry; }
  snapshot() { return structuredClone(this.entries); }
}
export function negotiateCapabilities(available = [], manifest = GEP_FEATURE_MANIFEST) {
  const requestedFeatures = [...manifest.required, ...manifest.optional, ...manifest.experimental];
  const supportedFeatures = requestedFeatures.filter(x => available.includes(x));
  return { manifestVersion: manifest.manifestVersion, requestedFeatures, supportedFeatures, unavailableFeatures: requestedFeatures.filter(x => !supportedFeatures.includes(x)) };
}

const FILES = ['raw-gep.jsonl','canonical-events.jsonl','snapshots.jsonl','diagnostics.jsonl'];
export class CaptureSessionWriter {
  constructor(root, options = {}) { this.root = root; this.options = options; this.handles = new Map(); this.sequence = 0; this.lastSnapshot = ''; }
  async start(options = {}) { if (this.directory) throw new Error('CAPTURE_ALREADY_ACTIVE'); const now = new Date(); this.sessionId = options.sessionId ?? randomUUID(); const name = `${now.toISOString().replaceAll(':','').replace(/\.\d{3}/,'')}-${this.sessionId}`; const pending = join(this.root, `.${name}.pending`); this.directory = join(this.root, name); await mkdir(this.root,{recursive:true}); await mkdir(pending); const session = { schemaVersion:1, appVersion:this.options.appVersion ?? '0.23.1', contentVersion:this.options.contentVersion ?? '0.23.1', startedAt:now.toISOString(), stoppedAt:null, runtimeMode:options.runtimeMode ?? 'MOCK', platform:options.platform ?? process.platform, gepStatus:options.gepStatus ?? 'GEP_INITIALIZING', dotaDetected:Boolean(options.dotaDetected), captureReason:options.captureReason ?? 'development', userNotes:options.userNotes ?? null, recovery:{cleanShutdown:false,lastSequence:0} }; await writeFile(join(pending,'session.json'),JSON.stringify(session,null,2)+'\n'); await writeFile(join(pending,'capabilities.json'),JSON.stringify(options.capabilities ?? negotiateCapabilities([]),null,2)+'\n'); for (const file of FILES) await writeFile(join(pending,file),''); await rename(pending,this.directory); for (const file of FILES) this.handles.set(file,await open(join(this.directory,file),'a')); this.session=session; return { sessionId:this.sessionId, directory:basename(this.directory), startedAt:session.startedAt };
  }
  async append(file, payload, meta = {}) { if (!this.handles.has(file)) throw new Error('CAPTURE_NOT_ACTIVE'); const row={schemaVersion:1,sessionId:this.sessionId,sequence:++this.sequence,receivedAt:meta.receivedAt??new Date().toISOString(),gameTimeSec:meta.gameTimeSec??null,source:meta.source??file.replace('.jsonl',''),payload}; await this.handles.get(file).appendFile(JSON.stringify(row)+'\n'); this.session.recovery.lastSequence=this.sequence; return row; }
  raw(payload,meta){return this.append('raw-gep.jsonl',payload,meta)} canonical(payload,meta){return this.append('canonical-events.jsonl',payload,meta)}
  snapshot(payload,meta={}) { const serialized=JSON.stringify(payload); if (!meta.force && serialized===this.lastSnapshot) return null; this.lastSnapshot=serialized; return this.append('snapshots.jsonl',payload,meta); }
  diagnostic(payload,meta){return this.append('diagnostics.jsonl',payload,meta)}
  async stop(reason='USER') { if (!this.directory) throw new Error('CAPTURE_NOT_ACTIVE'); for(const h of this.handles.values()){await h.sync();await h.close()} this.handles.clear(); this.session.stoppedAt=new Date().toISOString();this.session.recovery.cleanShutdown=true;this.session.stopReason=reason; await writeFile(join(this.directory,'session.json'),JSON.stringify(this.session,null,2)+'\n'); const summary={schemaVersion:1,sessionId:this.sessionId,stoppedAt:this.session.stoppedAt,sequenceCount:this.sequence,flushed:true};await writeFile(join(this.directory,'summary.json'),JSON.stringify(summary,null,2)+'\n');return summary; }
}

export async function readJsonl(file) { const text=await readFile(file,'utf8'); const rows=[]; for(const [i,line] of text.split(/\r?\n/).entries()){if(!line.trim())continue;try{rows.push(JSON.parse(line))}catch(error){throw new Error(`${basename(file)}:${i+1}: invalid JSON: ${error.message}`)}}return rows; }
export async function inspectCapture(dir) { const session=JSON.parse(await readFile(join(dir,'session.json'),'utf8')); const capabilities=JSON.parse(await readFile(join(dir,'capabilities.json'),'utf8')); const canonical=await readJsonl(join(dir,'canonical-events.jsonl')); const raw=await readJsonl(join(dir,'raw-gep.jsonl')); const all=[...raw,...canonical].sort((a,b)=>a.sequence-b.sequence); const eventCounts={};for(const x of all){const type=x.payload?.type??x.payload?.event??'unknown';eventCounts[type]=(eventCounts[type]??0)+1} return {requestedFeatures:capabilities.requestedFeatures??[],supportedFeatures:capabilities.supportedFeatures??[],unavailableFeatures:capabilities.unavailableFeatures??[],observedEventTypes:Object.keys(eventCounts),eventCounts,firstSeenAt:all[0]?.receivedAt??null,lastSeenAt:all.at(-1)?.receivedAt??null,parseErrors:0,ignoredEvents:0,duplicateEvents:0,outOfOrderEvents:all.filter((x,i)=>i&&x.sequence<=all[i-1].sequence).length,matchTransitions:canonical.filter(x=>['MATCH_STARTED','MATCH_ENDED','MATCH_RESET'].includes(x.payload?.type)).map(x=>x.payload.type),canonicalCoverage:[...new Set(canonical.map(x=>x.payload?.type).filter(Boolean))],roleContextCoverage:canonical.some(x=>x.payload?.role)?'OBSERVED':'UNAVAILABLE',reviewReadiness:canonical.some(x=>x.payload?.type==='MATCH_ENDED')?'READY':'PARTIAL',session}; }
export async function validateCapture(dir) { const errors=[],warnings=[]; let report; try{report=await inspectCapture(dir)}catch(e){return{status:'FAIL',errors:[e.message],warnings}} if(!report.session.schemaVersion||!report.session.startedAt)errors.push('session metadata is incomplete'); if(report.outOfOrderEvents)errors.push('sequence is not monotonic'); const required=['MATCH_STARTED','CLOCK','HERO'];for(const type of required)if(!report.canonicalCoverage.includes(type))warnings.push(`${type} not observed`);if(!report.session.stoppedAt)errors.push('capture was not flushed'); const serialized=JSON.stringify(report);if(/steam[_ ]?id|windows[_ ]?username|machine[_ ]?name|[A-Z]:\\\\Users\\\\/i.test(serialized))errors.push('privacy-sensitive field detected'); return{status:errors.length?'FAIL':warnings.length?'PASS_WITH_WARNINGS':'PASS',errors,warnings,report}; }
export async function replayCapture(dir) { const file=join(dir,'canonical-events.jsonl'); const events=await readJsonl(file); const finalSnapshot={};for(const row of events)Object.assign(finalSnapshot,row.payload?.state??{},row.payload?.snapshot??{});return{source:'canonical-events.jsonl',eventCount:events.length,finalSnapshot,review:{ready:events.some(x=>x.payload?.type==='MATCH_ENDED')},coachCall:events.map(x=>x.payload?.coachCall).filter(Boolean).at(-1)??null}; }
const PRIVATE_KEYS=/^(steam(id|_id)?|player(name)?|machine(name)?|windows(username)?|username|absolutePath|path)$/i;
function redactValue(value,salt){if(Array.isArray(value))return value.map(x=>redactValue(x,salt));if(value&&typeof value==='object'){return Object.fromEntries(Object.entries(value).filter(([k])=>!PRIVATE_KEYS.test(k)).map(([k,v])=>[k,redactValue(v,salt)]))}if(typeof value==='string'){if(/^[A-Z]:\\Users\\|^\/home\/|^\/Users\//i.test(value))return '[REDACTED_PATH]';if(/7656119\d{10}/.test(value))return `sha256:${createHash('sha256').update(salt+value).digest('hex').slice(0,16)}`}return value}
export async function redactCapture(input,output,{salt='dota-flow-export'}={}) { if(resolve(input)===resolve(output))throw new Error('output must differ from input');await rm(output,{recursive:true,force:true});await mkdir(output,{recursive:true});for(const name of await readdir(input)){const src=join(input,name),dst=join(output,name);if((await stat(src)).isDirectory())continue;const text=await readFile(src,'utf8');if(name.endsWith('.jsonl')){const lines=text.split(/\r?\n/).filter(Boolean).map(x=>JSON.stringify(redactValue(JSON.parse(x),salt)));await writeFile(dst,lines.join('\n')+(lines.length?'\n':''))}else if(name.endsWith('.json'))await writeFile(dst,JSON.stringify(redactValue(JSON.parse(text),salt),null,2)+'\n')}return{output:basename(output)}; }

export class DotaFlowRuntimeService {
  constructor({mode,adapter=null,captureRoot='captures',replayEvents=[]}={}) { this.mode=resolveRuntimeMode(mode);this.adapter=adapter;this.captureRoot=captureRoot;this.replayEvents=replayEvents;this.listeners=new Set();this.diagnostics=new RuntimeDiagnostics();this.snapshot={runtimeMode:this.mode,status:'STOPPED',capabilities:negotiateCapabilities([])}; }
  async start(){if(this.mode==='LIVE_GEP'&&!this.adapter){this.diagnostics.add('OVERWOLF_NOT_CONFIGURED','error',{remediation:'Install and whitelist the approved Overwolf Electron SDK application.'});throw Object.assign(new Error('Approved Overwolf runtime is not configured; LIVE_GEP failed closed'),{code:'OVERWOLF_NOT_CONFIGURED'})}this.snapshot.status=this.mode==='LIVE_GEP'?'GEP_INITIALIZING':'GEP_READY';if(this.adapter){const available=await this.adapter.getAvailableFeatures();this.snapshot.capabilities=negotiateCapabilities(available);await this.adapter.registerFeatures(this.snapshot.capabilities.supportedFeatures);this.unsubscribeAdapter=this.adapter.subscribe(x=>this.ingest(x));}for(const event of this.replayEvents)this.ingest(event);this.emit();}
  async stop(){this.unsubscribeAdapter?.();if(this.writer)await this.stopCapture();this.snapshot.status='STOPPED';this.emit()}
  getStatus(){return{runtimeMode:this.mode,status:this.snapshot.status}} getSnapshot(){return structuredClone(this.snapshot)} subscribe(listener){this.listeners.add(listener);return()=>this.listeners.delete(listener)} emit(){const s=this.getSnapshot();this.listeners.forEach(x=>x(s))} ingest(event){this.snapshot.lastEvent=event;this.snapshot.eventCount=(this.snapshot.eventCount??0)+1;void this.writer?.raw(event);this.emit()}
  async sendManualContext(command){if(!command||typeof command.type!=='string')throw new Error('INVALID_MANUAL_CONTEXT');this.snapshot.manualContext=structuredClone(command);this.emit()}
  async startCoachTimer(command){if(!command||!Number.isFinite(command.durationSec))throw new Error('INVALID_COACH_TIMER');this.snapshot.coachTimer={...command,startedAt:new Date().toISOString()};this.emit()}
  async startCapture(options={}){this.writer=new CaptureSessionWriter(this.captureRoot,{appVersion:'0.23.1',contentVersion:'0.23.1'});const result=await this.writer.start({...options,runtimeMode:this.mode,capabilities:this.snapshot.capabilities});this.snapshot.capture={active:true,...result};this.diagnostics.add('CAPTURE_ACTIVE');this.emit();return result}
  async stopCapture(){const result=await this.writer.stop();this.writer=null;this.snapshot.capture={active:false,...result};this.diagnostics.add('CAPTURE_STOPPED');this.emit();return result}
  getDiagnostics(){return this.diagnostics.snapshot()}
}
