export const SESSION_COACH_SCHEMA_VERSION = 1;
export const SESSION_INACTIVITY_MINUTES = 90;
export const SESSION_COACH_VERSION = '0.23.3';

export const PRIMARY_STATES = Object.freeze(['CALM','IN_FLOW','PROUD','HARD_CARRIED','BARELY_WON','DISAPPOINTED','THREW_GAME','REVENGE_QUEUE','TEAM_FRUSTRATION','TILTED','TIRED','UNFOCUSED','UNCERTAIN']);
export const QUEUE_MOTIVATIONS = Object.freeze(['ENJOYMENT','IMPROVEMENT','PLAY_WITH_FRIENDS','CLIMB_RANK','REVENGE_LOSS','PROVE_MYSELF','END_ON_WIN','BOREDOM','HABIT','UNSURE']);
export const READINESS_LEVELS = Object.freeze(['HIGH','MEDIUM','LOW','VERY_LOW','UNKNOWN']);
export const RECOMMENDATIONS = Object.freeze(['CONTINUE','CONTINUE_WITH_CAUTION','TAKE_SHORT_BREAK','SWITCH_TO_LOW_PRESSURE_MODE','END_RANKED_SESSION','END_SESSION','NOT_ENOUGH_DATA']);
export const PATTERN_THRESHOLDS = Object.freeze({ session:10,timeWindow:8,hero:6,role:8,established:20 });
export const SESSION_COACH_DEFAULTS = Object.freeze({ enabled:true,showCheckIn:true,showBreakSuggestions:true,dailyReflection:true,useTimeOfDay:true,useHeroHistory:true,useRoleHistory:true,useMatchReviewMetrics:true,allowFreeformNotes:false,inactivityMinutes:SESSION_INACTIVITY_MINUTES,storageMode:'LOCAL_INDEXED_DB',consentVersion:1 });
export const SESSION_COACH_WEIGHTS = Object.freeze({tilted:42,revengeState:36,threw:20,teamFrustration:18,revengeMotivation:34,proveMyself:18,repeatedNegative:14,lossStreak:8,lowEnergy:24,lowFocus:22,fourMatches:18,longSession:20,twoLongMatches:12,decliningScale:16,highDesireLowFocus:30,instantRequeue:12});

export const SESSION_COACH_COPY = Object.freeze({
  states:{CALM:'Calm',IN_FLOW:'In flow',PROUD:'Proud of my play',HARD_CARRIED:'Carried well',BARELY_WON:'Barely pulled through',DISAPPOINTED:'Disappointed',THREW_GAME:'I threw the game',REVENGE_QUEUE:'Want to win it back',TEAM_FRUSTRATION:'Frustrated with the team',TILTED:'Tilted',TIRED:'Tired',UNFOCUSED:'Low focus',UNCERTAIN:'Not sure'},
  motivations:{ENJOYMENT:'I am still enjoying it',IMPROVEMENT:'I want to practise',PLAY_WITH_FRIENDS:'Playing with friends',CLIMB_RANK:'I want to climb',REVENGE_LOSS:'I want to win back the loss',PROVE_MYSELF:'I want to prove the last game was a fluke',END_ON_WIN:'I want to end on a win',BOREDOM:'I have nothing else to do',HABIT:'Queuing from habit',UNSURE:'Not sure'},
  recommendations:{CONTINUE:{title:'Ready to continue',explanation:'Current signals support another deliberate game.'},CONTINUE_WITH_CAUTION:{title:'Continue with caution',explanation:'You can continue, but consider lowering the pressure.'},TAKE_SHORT_BREAK:{title:'Consider a short break',explanation:'A short reset may help decision stability.'},SWITCH_TO_LOW_PRESSURE_MODE:{title:'Lower the pressure',explanation:'Consider a lower-pressure mode for the next game.'},END_RANKED_SESSION:{title:'Consider ending ranked',explanation:'Several signals suggest ranked decision stability may be lower.'},END_SESSION:{title:'Consider ending the session',explanation:'Rest may be the safer alternative for this session.'},NOT_ENOUGH_DATA:{title:'Not enough data yet',explanation:'Add a few optional check-ins to build a useful signal.'}}
});

const clamp=n=>Math.max(0,Math.min(100,Math.round(n)));
const negative=new Set(['DISAPPOINTED','THREW_GAME','REVENGE_QUEUE','TEAM_FRUSTRATION','TILTED','TIRED','UNFOCUSED']);
const completed=xs=>xs.filter(x=>x&&!x.skipped&&x.primaryState);
const decreasing=values=>values.length>=3&&values.slice(1).every((x,i)=>x<=values[i])&&values.at(-1)<values[0];
const trace=(ruleId,contribution,explanation,evidence,severity='MEDIUM')=>({ruleId,contribution,explanation,evidence,severity});

export class SessionBoundaryPolicy {
  constructor({inactivityMinutes=SESSION_INACTIVITY_MINUTES}={}) { this.inactivityMinutes=inactivityMinutes; }
  shouldStartNew({activeSession,previousMatchEndedAt,nextMatchStartedAt,manuallyClosed=false}) { if(!activeSession||manuallyClosed||activeSession.endedAt)return true;if(!previousMatchEndedAt||!nextMatchStartedAt)return false;return new Date(nextMatchStartedAt)-new Date(previousMatchEndedAt)>=this.inactivityMinutes*60_000; }
  close(session,reason='MANUAL',at=new Date().toISOString()){return{...session,endedAt:at,closeReason:reason,lastActivityAt:at}}
}

function confidenceFor(checkIns,current,historyCount=0){const n=completed(checkIns).length,filled=['energy','focus','desireToPlay','queueMotivation'].filter(k=>current?.[k]!=null).length,context=Object.values(current?.matchContext??{}).filter(v=>v!=null).length;let score=Math.min(50,n*6)+filled*5+Math.min(10,context*2)+Math.min(15,historyCount/2);const level=historyCount>=40&&score>=75?'ESTABLISHED_PATTERN':historyCount>=15&&score>=55?'DEVELOPING_PATTERN':historyCount>=5&&score>=35?'EARLY_SIGNAL':'INSUFFICIENT';return{score:clamp(score),level,dataSufficiency:level};}
export class SessionCoachEngine {
  static evaluate(input={}){
    const all=input.checkIns??[],checks=completed(all),current=input.currentCheckIn??checks.at(-1),rules=[];
    if(!current)return unknownEvaluation();
    const W={...SESSION_COACH_WEIGHTS,...input.weights};
    const add=(condition,id,points,text,evidence,severity)=>{if(condition)rules.push(trace(id,points,text,evidence,severity))};
    add(current.primaryState==='TILTED','tilt.state',W.tilted,'Reported state is tilted.',{primaryState:current.primaryState},'HIGH');
    add(current.primaryState==='REVENGE_QUEUE','tilt.revenge-state',W.revengeState,'The next queue feels focused on winning back the last result.',{primaryState:current.primaryState},'HIGH');
    add(current.primaryState==='THREW_GAME','tilt.throw',W.threw,'The match ended with strong disappointment about a decision.',{primaryState:current.primaryState});
    add(current.primaryState==='TEAM_FRUSTRATION','tilt.team',W.teamFrustration,'Team frustration is present.',{primaryState:current.primaryState});
    add(current.queueMotivation==='REVENGE_LOSS','tilt.revenge-motivation',W.revengeMotivation,'Queue motivation is to win back a loss.',{queueMotivation:current.queueMotivation},'HIGH');
    add(current.queueMotivation==='PROVE_MYSELF','tilt.prove',W.proveMyself,'Queue motivation is to prove the last result was accidental.',{queueMotivation:current.queueMotivation});
    add(checks.length>=2&&checks.slice(-2).every(x=>negative.has(x.primaryState)),'tilt.repeated-negative',W.repeatedNegative,'Two recent check-ins share a difficult state.',{states:checks.slice(-2).map(x=>x.primaryState)});
    add((input.consecutiveLosses??lossStreak(checks))>=2,'tilt.loss-streak',W.lossStreak,'Two or more losses are present; loss alone is not treated as tilt.',{losses:input.consecutiveLosses??lossStreak(checks)},'LOW');
    add(current.energy!=null&&current.energy<=2,'fatigue.low-energy',W.lowEnergy,'Reported energy is low.',{energy:current.energy},'HIGH');
    add(current.focus!=null&&current.focus<=2,'fatigue.low-focus',W.lowFocus,'Reported focus is low.',{focus:current.focus},'HIGH');
    add((input.matchCount??checks.length)>=4,'fatigue.match-count',W.fourMatches,'This session has reached four matches.',{matchCount:input.matchCount??checks.length});
    add((input.totalDurationSec??0)>=150*60,'fatigue.duration',W.longSession,'The session has passed 150 minutes.',{totalDurationSec:input.totalDurationSec},'HIGH');
    add((input.longMatchCount??0)>=2,'fatigue.long-matches',W.twoLongMatches,'The session includes multiple long matches.',{longMatchCount:input.longMatchCount});
    add(decreasing(checks.map(x=>x.energy).filter(Number.isFinite)),'fatigue.energy-trend',W.decliningScale,'Reported energy has declined across recent check-ins.',{},'HIGH');
    add(decreasing(checks.map(x=>x.focus).filter(Number.isFinite)),'fatigue.focus-trend',W.decliningScale,'Reported focus has declined across recent check-ins.',{},'HIGH');
    add(current.desireToPlay===5&&current.focus!=null&&current.focus<=2,'impulse.desire-focus',W.highDesireLowFocus,'Desire to continue is high while focus is low.',{desireToPlay:current.desireToPlay,focus:current.focus},'HIGH');
    add((input.instantRequeueCount??0)>0,'impulse.instant-requeue',W.instantRequeue,'A quick requeue signal is present.',{instantRequeueCount:input.instantRequeueCount});
    const sum=prefix=>clamp(rules.filter(x=>x.ruleId.startsWith(prefix)).reduce((a,x)=>a+x.contribution,0));
    const tiltRisk=sum('tilt.'),fatigueRisk=sum('fatigue.'),requeueImpulse=clamp(sum('impulse.')+(current.queueMotivation==='REVENGE_LOSS'?18:0)+(current.primaryState==='REVENGE_QUEUE'?18:0));
    const readinessScore=clamp(82-tiltRisk*.42-fatigueRisk*.42-requeueImpulse*.25);
    const confidence=confidenceFor(checks,current,input.historyCount??checks.length);
    const level=readinessScore>=75?'HIGH':readinessScore>=55?'MEDIUM':readinessScore>=35?'LOW':'VERY_LOW';
    let recommendation=confidence.level==='INSUFFICIENT'&&checks.length<2?'NOT_ENOUGH_DATA':readinessScore<28?'END_RANKED_SESSION':readinessScore<45?'TAKE_SHORT_BREAK':readinessScore<65?'CONTINUE_WITH_CAUTION':'CONTINUE';
    if(fatigueRisk>=80&&input.totalDurationSec>=150*60)recommendation='END_SESSION';
    const primary=rules.sort((a,b)=>b.contribution-a.contribution).slice(0,3),copy=SESSION_COACH_COPY.recommendations[recommendation];
    const missingSignals=['energy','focus','desireToPlay'].filter(k=>current[k]==null).map(k=>`CURRENT_${k.toUpperCase()}`);if(!current.matchContext)missingSignals.push('MATCH_CONTEXT');
    return{readinessScore,readinessLevel:level,tiltRisk,fatigueRisk,requeueImpulse,recommendation:{type:recommendation,title:copy.title,explanation:copy.explanation,reasons:primary.map(x=>x.explanation),saferAlternative:recommendation==='CONTINUE'?null:'Choose a lower-pressure mode or pause before deciding.',confidence,dataSufficiency:confidence.dataSufficiency,dismissible:true,blocksUserAction:false},confidence,reasons:primary.map(x=>x.explanation),missingSignals,evidenceSummary:primary.map(x=>x.evidence),safeAlternatives:['Take a short break','Choose a lower-pressure mode','End ranked for today'],ruleTrace:rules};
  }
}
function unknownEvaluation(){const confidence={score:0,level:'INSUFFICIENT',dataSufficiency:'INSUFFICIENT'},copy=SESSION_COACH_COPY.recommendations.NOT_ENOUGH_DATA;return{readinessScore:null,readinessLevel:'UNKNOWN',tiltRisk:0,fatigueRisk:0,requeueImpulse:0,recommendation:{type:'NOT_ENOUGH_DATA',title:copy.title,explanation:copy.explanation,reasons:[],saferAlternative:null,confidence,dataSufficiency:'INSUFFICIENT',dismissible:true,blocksUserAction:false},confidence,reasons:[],missingSignals:['CURRENT_CHECK_IN'],evidenceSummary:[],safeAlternatives:[],ruleTrace:[]}}
function lossStreak(xs){let n=0;for(const x of [...xs].reverse()){if(x.matchContext?.resultKnown&&x.matchContext.won===false)n++;else break}return n}

export class PersonalPatternAnalyzer {
  constructor(thresholds=PATTERN_THRESHOLDS){this.thresholds=thresholds}
  analyze(checkIns,{computedAt=new Date().toISOString(),demo=false}={}){const xs=completed(checkIns),out=[];const make=(type,title,subset,min,summary)=>({id:`${type.toLowerCase()}-${subset.length}`,type,title,summary:subset.length>=min?summary:`Need ${min-subset.length} more relevant check-ins to test this pattern.`,sampleSize:subset.length,confidence:subset.length>=this.thresholds.established?'HIGH':subset.length>=min?'MEDIUM':'LOW',evidence:{reportedCheckIns:subset.length,demo},limitations:limitations(xs,subset),status:subset.length>=this.thresholds.established?'ESTABLISHED_PATTERN':subset.length>=min?'DEVELOPING_PATTERN':subset.length? 'EARLY_OBSERVATION':'INSUFFICIENT_DATA',computedAt,demo});
    const timed=xs.filter(x=>x.matchContext?.startedAt),late=timed.filter(x=>new Date(x.matchContext.startedAt).getHours()>=23);out.push(make('RISK_TIME_WINDOW','Late-session focus',late,this.thresholds.timeWindow,'In your history, late matches more often accompanied lower reported focus.'));
    const heroes=new Map(),roles=new Map();for(const x of xs){if(x.matchContext?.heroName)(heroes.get(x.matchContext.heroName)??heroes.set(x.matchContext.heroName,[]).get(x.matchContext.heroName)).push(x);if(x.matchContext?.role)(roles.get(x.matchContext.role)??roles.set(x.matchContext.role,[]).get(x.matchContext.role)).push(x)}
    const hero=[...heroes].sort((a,b)=>b[1].length-a[1].length)[0]??['Hero',[]];out.push(make('HERO_LOW_ENERGY_STABILITY',`${hero[0]} by reported energy`,hero[1],this.thresholds.hero,`With ${hero[0]}, your reported focus has been comparatively steady in similar energy states.`));
    const role=[...roles].sort((a,b)=>b[1].length-a[1].length)[0]??['Role',[]];out.push(make('ROLE_LOW_ENERGY_STABILITY',`${role[0]} stability`,role[1],this.thresholds.role,`On ${role[0]}, your reported focus has been comparatively steady in similar states.`));
    out.push(make('OPTIMAL_SESSION_LENGTH','Session length',xs,this.thresholds.session,'Your history suggests decision stability is usually strongest earlier in a session.'));return out;
  }
}
function limitations(all,subset){const a=[];if(subset.length<PATTERN_THRESHOLDS.established)a.push('Limited sample size');if(new Set(subset.map(x=>x.matchContext?.mode).filter(Boolean)).size>1)a.push('Different game modes');if(subset.some(x=>!x.matchContext?.resultKnown))a.push('Some match results are unknown');if(all.length&&new Date(all.at(-1).createdAt)-new Date(all[0].createdAt)<14*86400000)a.push('Data covers a short period');return a}

export function createSessionSummary(session,checkIns){const xs=completed(checkIns).filter(x=>x.sessionId===session.id),evaluation=SessionCoachEngine.evaluate({checkIns:xs,matchCount:xs.length,totalDurationSec:session.totalDurationSec??0,longMatchCount:xs.filter(x=>(x.matchContext?.durationSec??0)>=3600).length});const vals=k=>xs.map(x=>x[k]).filter(Number.isFinite);return{sessionId:session.id,startedAt:session.startedAt,lastActivityAt:session.lastActivityAt,endedAt:session.endedAt??null,matchCount:xs.length,totalDurationSec:session.totalDurationSec??0,wins:xs.filter(x=>x.matchContext?.won===true).length,losses:xs.filter(x=>x.matchContext?.won===false).length,averageEnergy:average(vals('energy')),averageFocus:average(vals('focus')),stateDistribution:Object.fromEntries(PRIMARY_STATES.map(s=>[s,xs.filter(x=>x.primaryState===s).length])),consecutiveLosses:lossStreak(xs),consecutiveWins:winStreak(xs),longMatchCount:xs.filter(x=>(x.matchContext?.durationSec??0)>=3600).length,instantRequeueCount:session.instantRequeueCount??0,readiness:evaluation.readinessLevel,tiltRisk:evaluation.tiltRisk,fatigueRisk:evaluation.fatigueRisk,requeueImpulse:evaluation.requeueImpulse,recommendation:evaluation.recommendation.type,confidence:evaluation.confidence,reasons:evaluation.reasons,missingSignals:evaluation.missingSignals}}
const average=xs=>xs.length?Math.round(xs.reduce((a,b)=>a+b,0)/xs.length*10)/10:null;function winStreak(xs){let n=0;for(const x of [...xs].reverse()){if(x.matchContext?.won===true)n++;else break}return n}

export class MemorySessionCoachRepository {
  constructor({namespace='USER'}={}){this.namespace=namespace;this.checkIns=new Map();this.reflections=new Map();this.sessions=new Map();this.settings={...SESSION_COACH_DEFAULTS};this.quarantine=[];this.lastExport=null}
  async saveCheckIn(x){validateCheckIn(x);this.checkIns.set(x.id,structuredClone(x));return this.getCheckIn(x.id)} async getCheckIn(id){return clone(this.checkIns.get(id)??null)} async listCheckIns(){return [...this.checkIns.values()].map(clone)} async updateCheckIn(id,patch){const old=this.checkIns.get(id);if(!old)throw storageError('CHECK_IN_NOT_FOUND');return this.saveCheckIn({...old,...patch,id})} async deleteCheckIn(id){return this.checkIns.delete(id)}
  async saveDailyReflection(x){if(!x?.id)throw storageError('INVALID_REFLECTION');this.reflections.set(x.id,structuredClone(x));return clone(x)} async listDailyReflections(){return [...this.reflections.values()].map(clone)} async saveSession(x){if(!x?.id)throw storageError('INVALID_SESSION');this.sessions.set(x.id,structuredClone(x));return clone(x)} async getSession(id){return clone(this.sessions.get(id)??null)} async listSessions(){return [...this.sessions.values()].map(clone)} async closeSession(id,reason='MANUAL'){const x=this.sessions.get(id);if(!x)throw storageError('SESSION_NOT_FOUND');return this.saveSession(new SessionBoundaryPolicy().close(x,reason))}
  async exportAll(){this.lastExport=new Date().toISOString();return{schemaVersion:SESSION_COACH_SCHEMA_VERSION,exportedAt:this.lastExport,storageMode:'LOCAL_MEMORY',namespace:this.namespace,checkIns:await this.listCheckIns(),dailyReflections:await this.listDailyReflections(),sessions:await this.listSessions(),privacySettings:await this.getPrivacySettings()}} async deleteAll(){this.checkIns.clear();this.reflections.clear();this.sessions.clear()} async getPrivacySettings(){return clone(this.settings)} async savePrivacySettings(x){this.settings={...this.settings,...x,storageMode:this.settings.storageMode};return this.getPrivacySettings()} async getPrivacyMetadata(){return{storageMode:'LOCAL_MEMORY',lastExport:this.lastExport,checkInCount:this.checkIns.size,reflectionCount:this.reflections.size,localDatabaseSize:null,consentVersion:this.settings.consentVersion}}
  ingest(records=[]){for(const x of records){try{validateCheckIn(x);this.checkIns.set(x.id,structuredClone(x))}catch(error){this.quarantine.push({record:x,error:error.code??'CORRUPT_RECORD'})}}return{accepted:this.checkIns.size,quarantined:this.quarantine.length}}
}
function clone(x){return x==null?x:structuredClone(x)}function storageError(code){return Object.assign(new Error(`Session Coach storage error: ${code}`),{code})}function validateCheckIn(x){if(!x||x.schemaVersion!==1||!x.id||!x.matchId||!x.sessionId)throw storageError('CORRUPT_CHECK_IN');if(!x.skipped&&!PRIMARY_STATES.includes(x.primaryState))throw storageError('INVALID_PRIMARY_STATE');for(const k of ['energy','focus','desireToPlay'])if(x[k]!=null&&(!Number.isInteger(x[k])||x[k]<1||x[k]>5))throw storageError(`INVALID_${k.toUpperCase()}`);return true}

export function createDemoSession(kind='HEALTHY'){const base={schemaVersion:1,sessionId:`demo-${kind.toLowerCase()}`,source:'DEMO',consentVersion:1,skipped:false,additionalStates:[],freeformNote:null};const specs=kind==='REVENGE'?[[false,'REVENGE_QUEUE',3,2,'REVENGE_LOSS'],[false,'TEAM_FRUSTRATION',2,1,'REVENGE_LOSS']]:kind==='FATIGUE'?[[true,'CALM',4,4,'ENJOYMENT'],[false,'CALM',3,3,'IMPROVEMENT'],[true,'TIRED',2,2,'HABIT'],[false,'TIRED',1,2,'HABIT']]:[[true,'CALM',4,4,'ENJOYMENT'],[false,'CALM',4,4,'IMPROVEMENT'],[true,'IN_FLOW',4,4,'ENJOYMENT']];return specs.map((x,i)=>({...base,id:`demo-${kind}-${i+1}`,matchId:`MOCK-${kind}-${i+1}`,createdAt:`2026-01-01T${String(18+i).padStart(2,'0')}:00:00.000Z`,completedAt:`2026-01-01T${String(18+i).padStart(2,'0')}:01:00.000Z`,primaryState:x[1],energy:x[2],focus:x[3],desireToPlay:kind==='REVENGE'?5:3,queueMotivation:x[4],matchContext:{heroName:i%2?'Crystal Maiden':'Ember Spirit',role:i%2?'hard support':'mid',durationSec:kind==='FATIGUE'?3900:2700,won:x[0],resultKnown:true,dataQuality:'DEMO',runtimeMode:'MOCK'}}))}
