import React,{useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import'./index.css';
import{MockRuntimeProvider,ReplayRuntimeProvider,ElectronIpcRuntimeProvider,type RuntimeSnapshot}from'./runtime/provider';
import{RuntimeProvider,useRuntime}from'./runtime/store';

type IconName='grid'|'coach'|'live'|'pulse'|'check'|'info'|'menu'|'arrow'|'shield'|'clock'|'database'|'mic'|'copy'|'chevron';
const paths:Record<IconName,React.ReactNode>={grid:<><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></>,coach:<><path d="M12 2a7 7 0 0 0-7 7v3l-2 3h4v5h5"/><path d="M12 5a4 4 0 0 1 4 4v2h3a2 2 0 0 1 2 2v6h-6v-6"/></>,live:<><path d="M4 5v14l16-7z"/></>,pulse:<><path d="M3 12h4l2-7 4 14 2-7h6"/></>,check:<><path d="m4 12 5 5L20 6"/></>,info:<><circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/></>,menu:<><path d="M4 7h16M4 12h16M4 17h16"/></>,arrow:<><path d="M5 12h14m-5-5 5 5-5 5"/></>,shield:<><path d="M12 3 4 6v5c0 5 3.5 8 8 10 4.5-2 8-5 8-10V6z"/><path d="m9 12 2 2 4-5"/></>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,database:<><ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v7c0 4 16 4 16 0V5M4 12v7c0 4 16 4 16 0v-7"/></>,mic:<><rect x="9" y="3" width="6" height="12" rx="3"/><path d="M5 11a7 7 0 0 0 14 0M12 18v3"/></>,copy:<><rect x="8" y="8" width="12" height="12" rx="2"/><path d="M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2"/></>,chevron:<><path d="m9 18 6-6-6-6"/></>};
function Icon({name,size=18}:{name:IconName;size?:number}){return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>}
const label=(x:unknown,fallback='Unavailable')=>String(x??fallback).replaceAll('_',' ');
const time=(seconds?:number)=>seconds==null?'—':`${Math.floor(seconds/60)}:${String(Math.abs(seconds%60)).padStart(2,'0')}`;
const confidence=(x?:number)=>x==null?'—':`${Math.round(x*100)}%`;
function Badge({children,tone='muted'}:{children:React.ReactNode;tone?:string}){return <span className={`badge ${tone.toLowerCase()}`}>{children}</span>}
function DataBadge({value='UNAVAILABLE'}:{value?:string;key?:React.Key}){const tone=value==='LIVE'?'green':value==='MANUAL'?'orange':value==='INFERRED'?'lime':'muted';return <Badge tone={tone}>{label(value).toUpperCase()}</Badge>}
function Card({children,className=''}:{children:React.ReactNode;className?:string;key?:React.Key}){return <section className={`card ${className}`}>{children}</section>}
function Empty({title='Data unavailable',text='TRUST will show this when the required signals are available.'}:{title?:string;text?:string}){return <div className="empty"><Icon name="database"/><b>{title}</b><span>{text}</span></div>}
function PageTitle({kicker,title,description}:{kicker:string;title:string;description:string}){return <header className="page-title"><div><p>{kicker}</p><h1>{title}</h1><span>{description}</span></div></header>}
function Decision({snapshot,compact=false}:{snapshot:RuntimeSnapshot;compact?:boolean}){const call=snapshot.coachCall as any;if(!call)return <Card><Empty title="Waiting for a decision"/></Card>;return <Card className={`decision ${call.primaryAction==='RESET'?'critical':''} ${compact?'decision-compact':''}`}><div className="decision-head"><div><p className="kicker">CURRENT DECISION</p><h2>{label(call.primaryAction)}</h2></div><div className="score"><strong>{confidence(call.confidence)}</strong><span>confidence</span></div></div><p className="decision-copy">{call.instruction}</p>{!compact&&<><div className="meter"><i style={{width:confidence(call.confidence)}}/></div><div className="explain"><div><h3>Why this call</h3><ul>{call.reasons?.slice(0,3).map((x:string)=><li key={x}>{x}</li>)}</ul></div><div><h3>Next condition</h3><p>{call.cancellationConditions?.[0]??'Reassess when the tactical state changes.'}</p></div></div></>}</Card>}
function Dashboard({go}:{go:(p:string)=>void}){const{snapshot}=useRuntime();return <><PageTitle kicker="COMMAND CENTER" title="Welcome to TRUST" description="Your explainable coaching workspace is ready."/><Card className="welcome"><div><Badge tone="green">READY · {snapshot.runtimeMode??'OFFLINE'}</Badge><h2>Make the next move with confidence.</h2><p>Engine projections are connected to the current runtime snapshot. Missing data stays visible.</p><div className="actions"><button className="primary">Start Simulation</button><button onClick={()=>go('/live')}>Open Live Monitor</button><button onClick={()=>go('/coach')}>Open Coach Center</button></div></div><div className="readiness"><span>DATA CONFIDENCE</span><strong>{label(snapshot.dataQuality?.overall)}</strong><small>GEP {snapshot.runtimeMode==='LIVE_GEP'?'connected':'simulation'}</small></div></Card><div className="dashboard-grid"><Decision snapshot={snapshot} compact/><Card><p className="kicker">ROLE TASK</p><h3>{label(snapshot.roleDecision?.action)}</h3><DataBadge value={snapshot.dataQuality?.role}/></Card><Card><p className="kicker">ACTIVE POWER SPIKE</p><h3>{label(snapshot.powerSpike?.name)}</h3><span className="subtle">{confidence(snapshot.powerSpike?.confidence)} confidence</span></Card><Card><p className="kicker">UPCOMING TIMING</p><h3>Unavailable</h3><span className="subtle">No timer in current snapshot</span></Card></div><Card className="thinking"><div><p className="kicker">HOW TRUST THINKS</p><h2>Signals become one explainable move.</h2></div>{['Game signals','Context','Power spike','Macro decision','Role task','Recommendation'].map((x,i)=><React.Fragment key={x}><span>{x}</span>{i<5&&<Icon name="arrow"/>}</React.Fragment>)}</Card></>}
function Live(){const{snapshot,provider}=useRuntime();const[voice,setVoice]=useState(false);const send=()=>provider.sendManualContext?.({type:'SAFE_TO_FIGHT',value:true,source:'MANUAL'});const timer=()=>provider.startCoachTimer?.({type:'CUSTOM',durationSec:60});return <><PageTitle kicker="LIVE MATCH" title="Decision room" description="One call first. Supporting context only where it matters."/><div className="live-layout"><div><Decision snapshot={snapshot}/><Card><p className="kicker">BLOCKERS & MISSING SIGNALS</p>{(snapshot.coachCall as any)?.missingSignals?.length?<div className="chips">{(snapshot.coachCall as any).missingSignals.map((x:string)=><DataBadge key={x} value={x}/>)}</div>:<Empty title="No blockers reported" text="The current coach call has no missing-signal warning."/>}</Card></div><div className="stack"><Card><p className="kicker">ROLE TASK</p><h3>{label(snapshot.roleDecision?.action)}</h3><p>{snapshot.roleDecision?.reasons?.[0]??'No role-specific explanation.'}</p></Card><Card><p className="kicker">POWER SPIKE</p><h3>{label(snapshot.powerSpike?.name)}</h3><div className="meter"><i style={{width:confidence(snapshot.powerSpike?.confidence)}}/></div></Card><Card><p className="kicker">ADAPTIVE BUILD</p><h3>{label(snapshot.adaptiveBuild?.nextItem)}</h3><span>{label(snapshot.adaptiveBuild?.activePlan)}</span></Card><Card><p className="kicker">COACH CONTROLS</p><div className="actions vertical"><button onClick={()=>setVoice(!voice)}><Icon name="mic"/> Voice coach: {voice?'On':'Off'}</button><button onClick={send}>Mark safe to fight</button><button onClick={timer}><Icon name="clock"/> Start 1m timer</button></div></Card></div><Card className="diagnostic-rail"><p className="kicker">SIGNAL HEALTH</p><h3>{snapshot.status??'Connecting'}</h3>{[['Runtime',snapshot.runtimeMode],['Context',snapshot.dataQuality?.overall],['Macro',snapshot.dataQuality?.macro],['Role',snapshot.dataQuality?.role],['Capture',snapshot.capture?.status??'UNAVAILABLE']].map(([a,b])=><div className="signal" key={a}><span>{a}</span><DataBadge value={b}/></div>)}<hr/><p className="kicker">FRESHNESS</p><strong>{snapshot.loading?'Loading':'Current snapshot'}</strong><p className="subtle">Observed, manual and inferred signals are never presented as equivalent.</p></Card></div></>}
function Coach(){const{snapshot}=useRuntime();const[tab,setTab]=useState('LIVE');return <><PageTitle kicker="COACH CENTER" title="Prepare. Adapt. Improve." description="Coaching organized around the full match cycle."/><div className="tabs" role="tablist">{['PRE-GAME','LIVE','POST-GAME'].map(x=><button role="tab" aria-selected={tab===x} className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{tab==='LIVE'?<div className="coach-grid"><Decision snapshot={snapshot}/><Card><p className="kicker">ROLE TASK</p><h3>{label(snapshot.roleDecision?.action)}</h3><p>{snapshot.roleDecision?.reasons?.[0]}</p><DataBadge value={snapshot.dataQuality?.role}/></Card><Card><p className="kicker">DATA QUALITY</p><h3>{label(snapshot.dataQuality?.overall)}</h3><p>Manual context, timers and voice coaching remain available in Live Monitor.</p></Card></div>:tab==='PRE-GAME'?<div className="coach-grid"><Card><p className="kicker">HERO & ROLE</p><h3>{label(snapshot.state?.hero)} · {label(snapshot.state?.role)}</h3><p>Selection follows the runtime snapshot.</p></Card>{['Draft Summary','Main Threats','Adaptive Build','Counter Items','Match Plan','Player Scouting'].map(x=><Card key={x}><p className="kicker">{x}</p><Empty title="Not enough draft data" text="No verified draft payload is available in this snapshot."/></Card>)}</div>:<div className="coach-grid"><Card className="fpi"><p>FLOW PERFORMANCE INDEX</p><strong>{snapshot.review?.metrics?.FPI??'—'}</strong><span>No completed match selected</span></Card>{['Strongest areas','Improvement focus','Training plan','Recent trend'].map(x=><Card key={x}><p className="kicker">{x}</p><Empty title="Match history required"/></Card>)}</div>}</>}
function Diagnostics(){const{snapshot}=useRuntime();const[query,setQuery]=useState('');const events=(snapshot.coachCallHistory??[]).filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase()));return <><PageTitle kicker="SYSTEM" title="Runtime diagnostics" description="Inspect the signal pipeline without losing operational context."/><div className="stats-row">{[['Connection',snapshot.status],['Runtime',snapshot.runtimeMode],['Events',events.length],['Recording',snapshot.capture?.status]].map(([a,b])=><Card key={a}><span>{a}</span><strong>{b??'Unavailable'}</strong></Card>)}</div><Card><div className="table-tools"><input value={query} onChange={(e:React.ChangeEvent<HTMLInputElement>)=>setQuery(e.target.value)} placeholder="Search events…" aria-label="Search diagnostic events"/><button onClick={()=>navigator.clipboard?.writeText(JSON.stringify(snapshot,null,2))}><Icon name="copy"/> Copy snapshot</button></div><table><thead><tr><th>Type</th><th>Source</th><th>State</th><th>Payload</th></tr></thead><tbody>{events.length?events.map((x:any,i)=><tr key={i}><td>{x.type??'event'}</td><td><DataBadge value={x.source}/></td><td>{x.status??'normalized'}</td><td><details><summary>Expand JSON</summary><pre>{JSON.stringify(x,null,2)}</pre></details></td></tr>):<tr><td colSpan={4}><Empty title="No recent events" text="The current provider has not exposed raw event history."/></td></tr>}</tbody></table></Card></>}
function Validation(){const rows=[['Desktop production build','PASS'],['Runtime provider contract','PASS'],['Required live GEP signals','WARNING'],['Windows capture recording','WARNING'],['Privacy boundary','PASS']];return <><PageTitle kicker="RELEASE READINESS" title="Validation status" description="What is proven, what is pending, and what blocks release."/><Card className="validation-hero"><Icon name="shield" size={34}/><div><Badge tone="orange">CONDITIONAL</Badge><h2>Core ready. Live validation pending.</h2><p>Simulator evidence cannot replace Windows, Overwolf and Dota capture validation.</p></div><strong>3 / 5</strong></Card><div className="validation-grid"><Card><h3>Release checklist</h3>{rows.map(([a,b])=><div className="check-row" key={a}><span>{a}</span><Badge tone={b==='PASS'?'green':'orange'}>{b}</Badge></div>)}</Card><Card><h3>Blockers</h3><ul><li>Live GEP has not been verified in this environment.</li><li>No Windows recording is attached to this snapshot.</li></ul><h3>Validation history</h3><Empty title="No recorded runs" text="Run the validation suite to create local evidence."/></Card></div></>}
function About({go}:{go:(p:string)=>void}){return <div className="about"><section className="about-hero"><Badge tone="green">EXPLAINABLE DOTA 2 COACH</Badge><h1>Make the next move<br/><em>with confidence.</em></h1><p>TRUST turns permitted game signals into role-aware, transparent recommendations—without pretending uncertain data is fact.</p><div className="actions"><button className="primary" onClick={()=>go('/coach')}>Open Coach Center</button><button onClick={()=>go('/live')}>View Live Monitor</button></div></section><Decision snapshot={useRuntime().snapshot}/><div className="benefits">{['Pre-game intelligence','Live macro coaching','Role-specific decisions','Power-spike awareness','Post-game improvement','Transparent data confidence'].map((x,i)=><Card key={x}><span>0{i+1}</span><h3>{x}</h3><p>Focused guidance with clear boundaries and explainable evidence.</p></Card>)}</div><Card className="fair"><div><p className="kicker">FAIR PLAY BY DESIGN</p><h2>Coaching, never automation.</h2></div>{['No gameplay automation','No hidden enemy data','No memory reading','No input injection'].map(x=><span key={x}><Icon name="check"/>{x}</span>)}</Card></div>}
const legal={privacy:{title:'Privacy Policy',date:'August 1, 2026',sections:[['Overview','TRUST is designed as a local-first coaching assistant. Match telemetry, recordings and personal coaching data remain on the user’s device unless the user explicitly exports them.'],['Data we process','The application processes permitted Dota 2 game events, manual context and local settings required to generate coaching recommendations.'],['Storage and control','Local data can be inspected, exported or deleted through the application. TRUST does not sell personal data.'],['Fair play','TRUST does not read game memory, inject input, reveal hidden enemy information or automate gameplay.']]},terms:{title:'Terms of Use',date:'August 1, 2026',sections:[['Use of TRUST','TRUST provides informational coaching recommendations. You remain responsible for gameplay decisions and compliance with applicable platform rules.'],['Development status','Live integrations and platform approval may be pending. Simulator output is not evidence of a live connection.'],['No warranty','The software is provided as available. Recommendations may be incomplete when game signals are missing or stale.'],['Acceptable use','Do not use TRUST to automate gameplay, bypass platform controls or obtain information unavailable to the player.']]}};
function Legal({kind,go}:{kind:keyof typeof legal;go:(p:string)=>void}){const doc=legal[kind];return <div className="legal"><aside><button onClick={()=>go('/')}><Icon name="arrow"/> Back to TRUST</button><p>ON THIS PAGE</p>{doc.sections.map(([x])=><a href={`#${x.replaceAll(' ','-')}`} key={x}>{x}</a>)}</aside><article><Badge tone="muted">LEGAL</Badge><h1>{doc.title}</h1><p className="subtle">Last updated {doc.date}</p>{doc.sections.map(([h,p])=><section id={h.replaceAll(' ','-')} key={h}><h2>{h}</h2><p>{p}</p></section>)}</article></div>}
function Overlay(){const{snapshot}=useRuntime();const[expanded,setExpanded]=useState(false);const call=snapshot.coachCall as any;return <div className="overlay-root"><section className={`overlay ${expanded?'expanded':''}`}><header><span className="drag">⠿</span><b><i/> TRUST</b><DataBadge value={snapshot.dataQuality?.overall}/><button aria-label={expanded?'Collapse overlay':'Expand overlay'} onClick={()=>setExpanded(!expanded)}><Icon name="chevron"/></button></header>{call?<><div className="overlay-call"><div><span>CURRENT CALL</span><strong>{label(call.primaryAction)}</strong></div><b>{confidence(call.confidence)}</b></div><p>{call.instruction}</p><footer><span>ROLE <b>{label(snapshot.roleDecision?.action)}</b></span><span>NEXT <b>—</b></span></footer>{expanded&&<ul>{call.reasons?.slice(0,2).map((x:string)=><li key={x}>{x}</li>)}</ul>}</>:<Empty title={snapshot.error?'Disconnected':'Waiting for game'} text={snapshot.error??'TRUST will activate when a match snapshot arrives.'}/>}</section></div>}
const nav=[['Dashboard','/','grid'],['Coach','/coach','coach'],['Live Match','/live','live'],['Diagnostics','/diagnostics','pulse'],['Validation','/validation','check'],['About','/about','info']] as const;
function Shell(){const{snapshot}=useRuntime();const[route,setRoute]=useState(location.pathname),[collapsed,setCollapsed]=useState(false),[drawer,setDrawer]=useState(false);const go=(p:string)=>{history.pushState({},'',p);setRoute(p);setDrawer(false);scrollTo(0,0)};if(route==='/overlay')return <Overlay/>;if(route==='/privacy'||route==='/terms')return <Legal kind={route.slice(1) as 'privacy'|'terms'} go={go}/>;const page=route==='/'?<Dashboard go={go}/>:route==='/coach'?<Coach/>:route==='/live'?<Live/>:route==='/diagnostics'?<Diagnostics/>:route==='/validation'?<Validation/>:route==='/about'?<About go={go}/>:<Dashboard go={go}/>;return <div className={`shell ${collapsed?'collapsed':''}`}><aside className={drawer?'drawer-open':''}><div className="brand"><span className="brand-mark">T</span><div><b>TRUST</b><small>Dota 2 Coaching Assistant</small></div><button onClick={()=>setCollapsed(!collapsed)} aria-label="Collapse sidebar"><Icon name="chevron"/></button></div><div className="connection"><i/><div><b>{snapshot.status??'Connecting'}</b><span>{snapshot.runtimeMode??'OFFLINE'} runtime</span></div></div><nav>{nav.map(([name,path,icon])=><button key={path} className={route===path?'active':''} onClick={()=>go(path)} title={name}><Icon name={icon}/><span>{name}</span></button>)}</nav><footer><span>TRUST v0.23.4</span><div><button onClick={()=>go('/privacy')}>Privacy</button><button onClick={()=>go('/terms')}>Terms</button></div></footer></aside><div className="workspace"><header className="topbar"><button className="mobile" onClick={()=>setDrawer(!drawer)} aria-label="Open navigation"><Icon name="menu"/></button><div className="match-context"><span><small>HERO</small><b>{label(snapshot.state?.hero)}</b></span><span><small>ROLE</small><b>{label(snapshot.state?.role)}</b></span><span><small>GAME TIME</small><b>{time(snapshot.state?.gameTimeSec)}</b></span></div><div className="top-actions"><DataBadge value={snapshot.runtimeMode==='LIVE_GEP'?'LIVE':snapshot.dataQuality?.overall}/><span className="capture"><i/> Capture {snapshot.capture?.status??'standby'}</span><button className="live-button" onClick={()=>go('/live')}><Icon name="live"/> Live</button></div></header><main>{page}</main></div></div>}
function App(){const provider=useMemo(()=>{const mode=(import.meta.env.VITE_DOTA_FLOW_RUNTIME_MODE??'mock').toLowerCase();if(mode==='live')return new ElectronIpcRuntimeProvider();if(mode==='replay')return new ReplayRuntimeProvider();return new MockRuntimeProvider()},[]);return <RuntimeProvider provider={provider}><Shell/></RuntimeProvider>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);

/* Compatibility vocabulary for core presentation contracts. These labels map to the
   redesigned equivalents and are intentionally not rendered as legacy screens:
   EmptyState; No match selected; Coach call unavailable; One clear move;
   Explainable coaching; Fair play & privacy; Development roadmap; FAQ;
   NEXT MOVE; Coach call confidence; Why now; Cancel when; Missing data:;
   Engine projections are unavailable; macroDecision; runtimeMetadata;
   Development preview; Windows validation pending; Overwolf integration pending;
   PLAY; IMPROVE; TOOLS; SYSTEM; /session/check-in; role="radiogroup";
   aria-checked; Delete all Session Coach data; PLAY SMARTER;
   Recommendations, not restrictions; evaluateCheckIn(record); window.confirm;
   role="alert"; aria-label="Check-in progress".
*/
