export const sessionCoachSchemaVersion = 1 as const;
export const SESSION_INACTIVITY_MINUTES = 90;
export type PrimaryState='CALM'|'IN_FLOW'|'PROUD'|'HARD_CARRIED'|'BARELY_WON'|'DISAPPOINTED'|'THREW_GAME'|'REVENGE_QUEUE'|'TEAM_FRUSTRATION'|'TILTED'|'TIRED'|'UNFOCUSED'|'UNCERTAIN';
export type QueueMotivation='ENJOYMENT'|'IMPROVEMENT'|'PLAY_WITH_FRIENDS'|'CLIMB_RANK'|'REVENGE_LOSS'|'PROVE_MYSELF'|'END_ON_WIN'|'BOREDOM'|'HABIT'|'UNSURE';
export interface MatchContext {heroId?:string|null;heroName?:string|null;role?:string|null;mode?:string|null;startedAt?:string|null;endedAt?:string|null;durationSec?:number|null;won?:boolean|null;resultKnown?:boolean;kills?:number|null;deaths?:number|null;assists?:number|null;FPI?:number|null;decisionSuccess?:number|null;callStability?:number|null;powerSpikeConversion?:number|null;objectiveConversion?:number|null;dataQuality?:string|null;runtimeMode?:string|null}
export interface PostMatchCheckIn {schemaVersion:1;id:string;matchId:string;sessionId:string;createdAt:string;completedAt:string|null;skipped:boolean;primaryState:PrimaryState|null;additionalStates:PrimaryState[];energy:1|2|3|4|5|null;focus:1|2|3|4|5|null;desireToPlay:1|2|3|4|5|null;queueMotivation:QueueMotivation|null;optionalNote:string|null;matchContext:MatchContext|null;source:'USER'|'MOCK'|'REPLAY';consentVersion:number}
export interface DailyReflection {schemaVersion:1;id:string;localDate:string;createdAt:string;sessionIds:string[];sessionRating:number|null;wasContinuingWorthIt:boolean|null;shouldHaveStoppedAfterMatch:number|null;mainFactors:string[];comparedWithSessionStart:'BETTER'|'SAME'|'WORSE'|'UNSURE';optionalNote:string|null;skipped:boolean}
export interface GameSession {schemaVersion:1;id:string;startedAt:string;lastActivityAt:string;endedAt:string|null;closeReason?:string;runtimeMode?:string|null}
export interface SessionCoachPrivacySettings {schemaVersion:1;enabled:boolean;showCheckIn:boolean;showBreakSuggestions:boolean;dailyReflection:boolean;useTimeOfDay:boolean;useHeroHistory:boolean;useRoleHistory:boolean;useMatchReviewMetrics:boolean;allowFreeformNotes:boolean;inactivityMinutes:number;disclosureAcceptedAt:string|null;consentVersion:number}
export const DEFAULT_PRIVACY_SETTINGS:SessionCoachPrivacySettings={schemaVersion:1,enabled:true,showCheckIn:true,showBreakSuggestions:true,dailyReflection:true,useTimeOfDay:true,useHeroHistory:true,useRoleHistory:true,useMatchReviewMetrics:true,allowFreeformNotes:false,inactivityMinutes:SESSION_INACTIVITY_MINUTES,disclosureAcceptedAt:null,consentVersion:1};
export interface SessionCoachExport {schemaVersion:1;exportedAt:string;storageMode:'LOCAL_INDEXED_DB';checkIns:PostMatchCheckIn[];dailyReflections:DailyReflection[];sessions:GameSession[];privacySettings:SessionCoachPrivacySettings}
export interface SessionCoachRepository {saveCheckIn(x:PostMatchCheckIn):Promise<PostMatchCheckIn>;getCheckIn(id:string):Promise<PostMatchCheckIn|null>;listCheckIns():Promise<PostMatchCheckIn[]>;updateCheckIn(id:string,patch:Partial<PostMatchCheckIn>):Promise<PostMatchCheckIn>;deleteCheckIn(id:string):Promise<boolean>;saveDailyReflection(x:DailyReflection):Promise<DailyReflection>;listDailyReflections():Promise<DailyReflection[]>;saveSession(x:GameSession):Promise<GameSession>;getSession(id:string):Promise<GameSession|null>;listSessions():Promise<GameSession[]>;closeSession(id:string,reason?:string):Promise<GameSession>;exportAll():Promise<SessionCoachExport>;deleteAll():Promise<void>;getPrivacySettings():Promise<SessionCoachPrivacySettings>;savePrivacySettings(x:Partial<SessionCoachPrivacySettings>):Promise<SessionCoachPrivacySettings>}
const DB='dota-flow-session-coach-v1',STORE='records';
const isScale=(x:unknown)=>x==null||(Number.isInteger(x)&&Number(x)>=1&&Number(x)<=5);
const states=new Set<PrimaryState>(['CALM','IN_FLOW','PROUD','HARD_CARRIED','BARELY_WON','DISAPPOINTED','THREW_GAME','REVENGE_QUEUE','TEAM_FRUSTRATION','TILTED','TIRED','UNFOCUSED','UNCERTAIN']);
export function isValidCheckIn(x:unknown):x is PostMatchCheckIn{const r=x as PostMatchCheckIn;return Boolean(r&&r.schemaVersion===1&&r.id&&r.matchId&&r.sessionId&&(r.skipped||states.has(r.primaryState as PrimaryState))&&isScale(r.energy)&&isScale(r.focus)&&isScale(r.desireToPlay))}
/** IndexedDB-only browser adapter. It has no network or Node filesystem capability. */
export class IndexedDbSessionCoachRepository implements SessionCoachRepository {
  private async db():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open(DB,1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(STORE))request.result.createObjectStore(STORE,{keyPath:'key'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(new Error('SESSION_COACH_STORAGE_UNAVAILABLE'))})}
  private async put(key:string,value:unknown){const db=await this.db();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put({key,value});tx.oncomplete=()=>resolve();tx.onerror=()=>reject(new Error('SESSION_COACH_STORAGE_WRITE_FAILED'))});db.close()}
  private async get<T>(key:string,fallback:T):Promise<T>{const db=await this.db();const value=await new Promise<T>(resolve=>{const req=db.transaction(STORE).objectStore(STORE).get(key);req.onsuccess=()=>resolve((req.result?.value??fallback) as T);req.onerror=()=>resolve(fallback)});db.close();return value}
  async saveCheckIn(x:PostMatchCheckIn){if(!isValidCheckIn(x))throw new Error('INVALID_CHECK_IN');await this.put(`checkIn:${x.id}`,structuredClone(x));return structuredClone(x)}
  async getCheckIn(id:string){const x=await this.get<unknown>(`checkIn:${id}`,null);return isValidCheckIn(x)?structuredClone(x):null}
  async listCheckIns(){return(await this.entries('checkIn:')).map(x=>x.value).filter(isValidCheckIn).map(x=>structuredClone(x))}
  async updateCheckIn(id:string,patch:Partial<PostMatchCheckIn>){const current=await this.getCheckIn(id);if(!current)throw new Error('CHECK_IN_NOT_FOUND');return this.saveCheckIn({...current,...patch,id})}
  async deleteCheckIn(id:string){return this.remove(`checkIn:${id}`)}
  async saveDailyReflection(x:DailyReflection){if(!x?.id||x.schemaVersion!==1)throw new Error('INVALID_REFLECTION');await this.put(`reflection:${x.id}`,x);return structuredClone(x)}
  async listDailyReflections(){return(await this.entries('reflection:')).map(x=>x.value as DailyReflection).filter(x=>x?.schemaVersion===1&&Boolean(x.id))}
  async saveSession(x:GameSession){if(!x?.id||x.schemaVersion!==1)throw new Error('INVALID_SESSION');await this.put(`session:${x.id}`,x);return structuredClone(x)}
  async getSession(id:string){const x=await this.get<GameSession|null>(`session:${id}`,null);return x?.schemaVersion===1?x:null}
  async listSessions(){return(await this.entries('session:')).map(x=>x.value as GameSession).filter(x=>x?.schemaVersion===1&&Boolean(x.id))}
  async closeSession(id:string,reason='MANUAL'){const x=await this.getSession(id);if(!x)throw new Error('SESSION_NOT_FOUND');return this.saveSession({...x,endedAt:new Date().toISOString(),lastActivityAt:new Date().toISOString(),closeReason:reason})}
  async getPrivacySettings(){return{...DEFAULT_PRIVACY_SETTINGS,...await this.get('settings',{})}}
  async savePrivacySettings(x:Partial<SessionCoachPrivacySettings>){const next={...await this.getPrivacySettings(),...x,schemaVersion:1 as const};await this.put('settings',next);return next}
  async exportAll():Promise<SessionCoachExport>{return{schemaVersion:1,exportedAt:new Date().toISOString(),storageMode:'LOCAL_INDEXED_DB',checkIns:await this.listCheckIns(),dailyReflections:await this.listDailyReflections(),sessions:await this.listSessions(),privacySettings:await this.getPrivacySettings()}}
  async deleteAll(){const db=await this.db();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).clear();tx.oncomplete=()=>resolve();tx.onerror=()=>reject(new Error('SESSION_COACH_STORAGE_DELETE_FAILED'))});db.close()}
  private async entries(prefix:string):Promise<Array<{key:string;value:unknown}>>{const db=await this.db();const rows=await new Promise<Array<{key:string;value:unknown}>>(resolve=>{const out:Array<{key:string;value:unknown}>=[],req=db.transaction(STORE).objectStore(STORE).openCursor();req.onsuccess=()=>{const cursor=req.result;if(!cursor)return resolve(out);if(String(cursor.value?.key).startsWith(prefix))out.push(cursor.value);cursor.continue()};req.onerror=()=>resolve(out)});db.close();return rows}
  private async remove(key:string){const exists=await this.get(key,null)!==null,db=await this.db();await new Promise<void>(resolve=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(key);tx.oncomplete=()=>resolve();tx.onerror=()=>resolve()});db.close();return exists}
}
export const STATE_GROUPS=[{title:'Positive',states:[['IN_FLOW','In flow'],['PROUD','Proud of my play'],['HARD_CARRIED','Carried well'],['CALM','Calm']]},{title:'Heavy or neutral',states:[['BARELY_WON','Barely pulled through'],['DISAPPOINTED','Disappointed'],['TIRED','Tired'],['UNFOCUSED','Low focus']]},{title:'Impulsive',states:[['REVENGE_QUEUE','Want to win it back'],['THREW_GAME','I threw the game'],['TEAM_FRUSTRATION','Team frustration'],['TILTED','Tilted']]},{title:'Unsure',states:[['UNCERTAIN','Not sure']]}] as const;
export const MOTIVATION_OPTIONS:Array<[QueueMotivation,string]>=[['ENJOYMENT','Still enjoying it'],['IMPROVEMENT','Practise and improve'],['PLAY_WITH_FRIENDS','Play with friends'],['CLIMB_RANK','Climb rank'],['REVENGE_LOSS','Win back the loss'],['PROVE_MYSELF','Prove myself'],['END_ON_WIN','End on a win'],['BOREDOM','Boredom'],['HABIT','Habit'],['UNSURE','Not sure']];
export interface CheckInResult {readinessScore:number;readinessLevel:'HIGH'|'MEDIUM'|'LOW'|'VERY_LOW';recommendation:'CONTINUE'|'CONTINUE_WITH_CAUTION'|'TAKE_SHORT_BREAK'|'END_RANKED_SESSION';title:string;reasons:string[];confidence:'INSUFFICIENT'|'EARLY_SIGNAL';safeAlternative:string|null}
/** Presentation model mirrors the named MVP rules without putting scoring in JSX. */
export function evaluateCheckIn(x:PostMatchCheckIn):CheckInResult{let tilt=0,fatigue=0,impulse=0;const reasons:string[]=[];const add=(condition:boolean,points:number,reason:string,target:'tilt'|'fatigue'|'impulse')=>{if(!condition)return;if(target==='tilt')tilt+=points;if(target==='fatigue')fatigue+=points;if(target==='impulse')impulse+=points;reasons.push(reason)};add(x.primaryState==='TILTED',42,'You reported feeling tilted.','tilt');add(x.primaryState==='REVENGE_QUEUE',36,'You reported wanting to immediately win it back.','tilt');add(x.primaryState==='TEAM_FRUSTRATION',18,'Team frustration is present.','tilt');add(x.queueMotivation==='REVENGE_LOSS',34,'The next queue is motivated by winning back a loss.','tilt');add(x.energy!=null&&x.energy<=2,24,'Reported energy is low.','fatigue');add(x.focus!=null&&x.focus<=2,22,'Reported focus is low.','fatigue');add(x.desireToPlay===5&&x.focus!=null&&x.focus<=2,30,'Desire to continue is high while focus is low.','impulse');const score=Math.max(0,Math.min(100,Math.round(82-Math.min(100,tilt)*.42-Math.min(100,fatigue)*.42-Math.min(100,impulse)*.25))),level=score>=75?'HIGH':score>=55?'MEDIUM':score>=35?'LOW':'VERY_LOW';const recommendation=score<35?'END_RANKED_SESSION':score<50?'TAKE_SHORT_BREAK':score<70?'CONTINUE_WITH_CAUTION':'CONTINUE';const title={CONTINUE:'Ready to continue',CONTINUE_WITH_CAUTION:'Continue with caution',TAKE_SHORT_BREAK:'Consider a short break',END_RANKED_SESSION:'Consider ending ranked'}[recommendation];return{readinessScore:score,readinessLevel:level,recommendation,title,reasons:reasons.slice(0,3),confidence:'INSUFFICIENT',safeAlternative:recommendation==='CONTINUE'?null:'Pause or choose a lower-pressure mode before deciding.'}}
