import React,{useEffect,useState}from'react';
import type{RuntimeSnapshot}from'./runtime/provider';
import{useAppSettings}from'./app-settings';
import{deriveMatchStage,selectPresentedCoachCall,stageTranslationKey}from'./phase-aware';
import'./window-frame.css';
import'./themes-settings.css';

type WindowState={compact:boolean;alwaysOnTop:boolean};
const fallbackState:WindowState={compact:true,alwaysOnTop:false};
const time=(seconds?:number)=>seconds==null?'—':`${seconds<0?'-':''}${Math.floor(Math.abs(seconds)/60)}:${String(Math.abs(seconds)%60).padStart(2,'0')}`;
const confidence=(value?:number)=>value==null?'—':`${Math.round(value*100)}%`;
function PinIcon(){return <svg aria-hidden="true" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="m14 4 6 6-3 1-4 4-1 5-3-3-4 4-2-2 4-4-3-3 5-1 4-4z"/></svg>}
function ExpandIcon(){return <svg aria-hidden="true" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M8 3H3v5M16 3h5v5M8 21H3v-5M16 21h5v-5"/></svg>}

export function WindowFrame({snapshot,children}:{snapshot:RuntimeSnapshot;children:React.ReactNode}){
  const{t,value,text}=useAppSettings();const[state,setState]=useState<WindowState>(fallbackState);const[busy,setBusy]=useState(false);const api=window.dotaFlowRuntime;
  useEffect(()=>{let active=true;if(!api)return;void api.invoke('window:get-state').then(result=>{if(!active||!result||typeof result!=='object')return;const next=result as Partial<WindowState>;setState({compact:next.compact!==false,alwaysOnTop:next.alwaysOnTop===true})}).catch(error=>console.error('[TRUST] Failed to load window state',error));return()=>{active=false}},[api]);
  const applyState=(result:unknown,compact:boolean,alwaysOnTop:boolean):WindowState=>{const next=result&&typeof result==='object'?result as Partial<WindowState>:{};const resolved={compact:next.compact??compact,alwaysOnTop:next.alwaysOnTop??alwaysOnTop};setState(resolved);return resolved};
  const focusModeControl=(compact:boolean)=>requestAnimationFrame(()=>{document.querySelector<HTMLButtonElement>(`[data-window-mode-control="${compact?'expand':'compact'}"]`)?.focus()});
  const setCompact=async(compact:boolean)=>{if(busy)return;setBusy(true);const previous=state;let resolvedCompact=compact;setState({...state,compact});try{if(api){const resolved=applyState(await api.invoke('window:set-compact',{compact}),compact,state.alwaysOnTop);resolvedCompact=resolved.compact}}catch(error){setState(previous);resolvedCompact=previous.compact;console.error('[TRUST] Failed to change compact window mode',error)}finally{setBusy(false);focusModeControl(resolvedCompact)}};
  const toggleAlwaysOnTop=async()=>{if(busy)return;setBusy(true);const previous=state,alwaysOnTop=!state.alwaysOnTop;setState({...state,alwaysOnTop});try{if(!api)return;applyState(await api.invoke('window:set-always-on-top',{alwaysOnTop}),state.compact,alwaysOnTop)}catch(error){setState(previous);console.error('[TRUST] Failed to change always-on-top mode',error)}finally{setBusy(false)}};
  const closeWindow=async()=>{if(api){await api.invoke('window:close');return}window.close()};
  const call=selectPresentedCoachCall(snapshot);const stage=t(stageTranslationKey(deriveMatchStage(snapshot)));const instruction=call.instructionKey?t(call.instructionKey):text(call.instruction);
  if(state.compact)return <div className="compact-window-root" aria-busy={busy}><section className="compact-window" aria-label={t('window.compactLabel')}><header className="window-drag-region"><span className="compact-brand"><i/>TRUST</span><span className="compact-stage">{stage}</span><button className={`window-no-drag ${state.alwaysOnTop?'active':''}`} disabled={busy} aria-pressed={state.alwaysOnTop} aria-label={t('window.alwaysOnTop')} title={t('window.alwaysOnTop')} onClick={(event:React.MouseEvent<HTMLButtonElement>)=>{event.stopPropagation();void toggleAlwaysOnTop()}}><PinIcon/></button><button data-window-mode-control="expand" className="window-no-drag" disabled={busy} aria-expanded={false} aria-label={t('window.expand')} title={t('window.expand')} onClick={()=>void setCompact(false)}><ExpandIcon/></button><button className="window-no-drag close-control" aria-label={t('window.close')} title={t('window.close')} onClick={()=>void closeWindow()}>×</button></header><button className="compact-window-body window-no-drag" disabled={busy} onClick={()=>void setCompact(false)} aria-expanded={false} aria-label={t('window.expand')}><span className="compact-context"><small>{value(snapshot.state?.hero,'Hero')}</small><b>{time(snapshot.state?.gameTimeSec)}</b></span><span className="compact-call"><small>{t('decision.current')}</small><strong>{value(call.primaryAction)}</strong><em>{instruction}</em></span><span className="compact-confidence"><b>{confidence(call.confidence)}</b><small>{t('common.confidence')}</small></span></button></section></div>;
  return <div className="window-frame-host" aria-busy={busy}><div className="custom-titlebar window-drag-region"><span className="custom-titlebar-brand"><i/>TRUST <small>{t('app.subtitle')}</small></span><div className="window-controls window-no-drag" aria-label="Window controls"><button className={state.alwaysOnTop?'active':''} disabled={busy} aria-pressed={state.alwaysOnTop} aria-label={t('window.alwaysOnTop')} title={state.alwaysOnTop?t('window.disableAlwaysOnTop'):t('window.alwaysOnTop')} onClick={()=>void toggleAlwaysOnTop()}><PinIcon/></button><button data-window-mode-control="compact" disabled={busy} aria-expanded={true} aria-label={t('window.compact')} title={t('window.compact')} onClick={()=>void setCompact(true)}><span className="window-minus">−</span></button><button className="close-control" aria-label={t('window.close')} title={t('window.close')} onClick={()=>void closeWindow()}>×</button></div></div><div className="window-frame-content">{children}</div></div>;
}
